name: .NET

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build & Check
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    # FIXME: Tools won't run in .NET 6.0 unless you install 3.1.x LTS side by side.
    # https://itnext.io/how-to-support-multiple-net-sdks-in-github-actions-workflows-b988daa884e
    - name: Install .NET 3.1.x LTS
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Install .NET 6.0.x LTS
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore Tools
      run: dotnet tool restore

    - name: Restore inspectcode cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/inspectcode
        key: inspectcode-${{ hashFiles('.config/dotnet-tools.json', '.github/workflows/pr-build-check.yml', 'src/MilkiBotFramework.sln*') }}

    - name: Restore dependencies
      run: dotnet restore ./src

    - name: Build
      run: dotnet build ./src --no-restore

    - name: InspectCode
      run: dotnet jb inspectcode ./src/MilkiBotFramework.sln --no-build --output="inspectcodereport.xml" --caches-home="inspectcode" --verbosity=WARN

    - name: NVika
      run: dotnet nvika parsereport "${{github.workspace}}/inspectcodereport.xml"

